# Generated by Django 5.2.13 on 2026-04-21 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_mastercode_code_group_mastercode_library_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('follow_up_with', models.CharField(blank=True, max_length=255, null=True)),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_issues', to='reports.dailyreport')),
                ('master_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.mastercode')),
            ],
        ),
    ]
