# Generated by Django 5.2.13 on 2026-04-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_blockedissue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyreport',
            old_name='report_date',
            new_name='reference_date',
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
