# Generated by Django 5.2.13 on 2026-04-21 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_rename_report_date_dailyreport_reference_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_type', models.CharField(choices=[('weather', 'Weather'), ('qc_result', 'QC Result'), ('severity', 'Severity'), ('followup', 'Follow Up'), ('workforce', 'Workforce'), ('skill_level', 'Skill Level'), ('usage_type', 'Usage Type'), ('uom', 'UOM'), ('status', 'Status')], max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blockedissue',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='workprogress',
            name='boq_code',
        ),
        migrations.RemoveField(
            model_name='workprogress',
            name='description',
        ),
        migrations.AddField(
            model_name='blockedissue',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mastercode',
            name='display_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workprogress',
            name='master_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.mastercode'),
        ),
        migrations.AddField(
            model_name='workprogress',
            name='status',
            field=models.ForeignKey(blank=True, limit_choices_to={'list_type': 'status'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_progress_statuses', to='reports.lookupitem'),
        ),
        migrations.AlterField(
            model_name='blockedissue',
            name='follow_up_with',
            field=models.ForeignKey(blank=True, limit_choices_to={'list_type': 'followup'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_issue_followups', to='reports.lookupitem'),
        ),
        migrations.AlterField(
            model_name='blockedissue',
            name='severity',
            field=models.ForeignKey(blank=True, limit_choices_to={'list_type': 'severity'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_issue_severities', to='reports.lookupitem'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='weather',
            field=models.ForeignKey(blank=True, limit_choices_to={'list_type': 'weather'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_reports_weather', to='reports.lookupitem'),
        ),
        migrations.AlterField(
            model_name='workprogress',
            name='qc_result',
            field=models.ForeignKey(blank=True, limit_choices_to={'list_type': 'qc_result'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_progress_qc_results', to='reports.lookupitem'),
        ),
    ]
