# Generated by Django 5.2.13 on 2026-04-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_lookupitem_remove_blockedissue_reason_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyreport',
            old_name='temperature',
            new_name='weather_fetch_status',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='weather',
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='temperature_api',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='temperature_manual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='weather_condition_api',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='weather_condition_manual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='weather_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='weather_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='weather_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='weather_override_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='weather_source',
            field=models.CharField(blank=True, default='api', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='lookupitem',
            name='list_type',
            field=models.CharField(choices=[('qc_result', 'QC Result'), ('severity', 'Severity'), ('followup', 'Follow Up'), ('workforce', 'Workforce'), ('skill_level', 'Skill Level'), ('usage_type', 'Usage Type'), ('uom', 'UOM'), ('status', 'Status')], max_length=50),
        ),
    ]
