# Generated by Django 5.2.13 on 2026-04-21 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_rename_temperature_dailyreport_weather_fetch_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookupitem',
            name='list_type',
            field=models.CharField(choices=[('qc_result', 'QC Result'), ('severity', 'Severity'), ('followup', 'Follow Up'), ('workforce', 'Workforce'), ('skill_level', 'Skill Level'), ('usage_type', 'Usage Type'), ('uom', 'UOM'), ('status', 'Status'), ('visit_type', 'Visit Type')], max_length=50),
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to='reports.dailyreport')),
                ('visit_type', models.ForeignKey(blank=True, limit_choices_to={'list_type': 'visit_type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_visit_types', to='reports.lookupitem')),
            ],
        ),
    ]
