# Generated by Django 5.2.13 on 2026-04-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_lookupitem_list_type_sitevisit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyreport',
            old_name='temperature_api',
            new_name='temperature',
        ),
        migrations.RenameField(
            model_name='dailyreport',
            old_name='weather_condition_api',
            new_name='weather_condition',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='temperature_manual',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='weather_condition_manual',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='weather_fetch_status',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='weather_fetched_at',
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='weather_source',
            field=models.CharField(blank=True, choices=[('api_confirmed', 'API Confirmed'), ('manual_override', 'Manual Override')], max_length=30, null=True),
        ),
    ]
