# Generated by Django 5.2.13 on 2026-04-21 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_rename_temperature_api_dailyreport_temperature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkforceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(blank=True, max_length=255, null=True)),
                ('regular_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overtime_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workforce_entries', to='reports.dailyreport')),
                ('master_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.mastercode')),
                ('skill_level', models.ForeignKey(blank=True, limit_choices_to={'list_type': 'skill_level'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workforce_entry_skill_levels', to='reports.lookupitem')),
                ('workforce_type', models.ForeignKey(blank=True, limit_choices_to={'list_type': 'workforce'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workforce_entry_types', to='reports.lookupitem')),
            ],
        ),
    ]
