# Generated by Django 5.2.13 on 2026-04-21 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_workforceentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_usages', to='reports.dailyreport')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.equipmentmaster')),
                ('master_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.mastercode')),
                ('usage_type', models.ForeignKey(blank=True, limit_choices_to={'list_type': 'usage_type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_usage_types', to='reports.lookupitem')),
            ],
        ),
    ]
