# Generated by Django 5.2.13 on 2026-04-21 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_equipmentusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_note', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_receipts', to='reports.dailyreport')),
                ('master_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.mastercode')),
                ('uom', models.ForeignKey(blank=True, limit_choices_to={'list_type': 'uom'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_receipt_uoms', to='reports.lookupitem')),
            ],
        ),
    ]
