# Generated by Django 5.2.13 on 2026-04-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_materialreceipt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockedissue',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='dailyreport',
            options={'ordering': ['-reference_date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='equipmentusage',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='materialreceipt',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='sitevisit',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='workforceentry',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='workprogress',
            options={'ordering': ['id']},
        ),
        migrations.AddConstraint(
            model_name='dailyreport',
            constraint=models.UniqueConstraint(fields=('project', 'reference_date'), name='unique_daily_report_per_project_per_date'),
        ),
    ]
