# Generated by Django 5.2.13 on 2026-04-30 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_alter_blockedissue_options_alter_dailyreport_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_code', models.CharField(max_length=10, unique=True)),
                ('phase_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Project Phase',
                'verbose_name_plural': 'Project Phases',
                'ordering': ['display_order', 'phase_code'],
            },
        ),
        migrations.AlterModelOptions(
            name='lookupitem',
            options={'ordering': ['list_type', 'sort_order', 'value']},
        ),
        migrations.AlterModelOptions(
            name='mastercode',
            options={'ordering': ['project_phase__display_order', 'category__symbol', 'subcategory__symbol', 'document_type__symbol'], 'verbose_name': 'Master Code', 'verbose_name_plural': 'Master Codes'},
        ),
        migrations.AddField(
            model_name='mastercode',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mastercode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mastercode',
            name='code',
            field=models.CharField(blank=True, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mastercode',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_codes', to='reports.category'),
        ),
        migrations.AddField(
            model_name='mastercode',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_codes', to='reports.documenttype'),
        ),
        migrations.AddField(
            model_name='mastercode',
            name='project_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_codes', to='reports.projectphase'),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='reports.category')),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
                'ordering': ['category__symbol', 'symbol'],
                'unique_together': {('category', 'symbol')},
            },
        ),
        migrations.AlterField(
            model_name='mastercode',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_codes', to='reports.subcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='mastercode',
            unique_together={('project_phase', 'category', 'subcategory', 'document_type')},
        ),
        migrations.RemoveField(
            model_name='mastercode',
            name='code_group',
        ),
        migrations.RemoveField(
            model_name='mastercode',
            name='library_id',
        ),
        migrations.RemoveField(
            model_name='mastercode',
            name='work_item',
        ),
        migrations.RemoveField(
            model_name='mastercode',
            name='work_type',
        ),
    ]
