# Generated by Django 5.2.13 on 2026-05-07 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_category_documenttype_projectphase_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReportChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=150)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily Report Change Log',
                'verbose_name_plural': 'Daily Report Change Logs',
                'ordering': ['-edited_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='blockedissue',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dailyreport',
            options={'ordering': ['-reference_date', '-created_at'], 'verbose_name': 'Daily Report', 'verbose_name_plural': 'Daily Reports'},
        ),
        migrations.AlterModelOptions(
            name='equipmentusage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='materialreceipt',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sitevisit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workforceentry',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workprogress',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='dailyreport',
            name='unique_daily_report_per_project_per_date',
        ),
        migrations.RemoveField(
            model_name='blockedissue',
            name='follow_up_with',
        ),
        migrations.RemoveField(
            model_name='blockedissue',
            name='master_code',
        ),
        migrations.RemoveField(
            model_name='blockedissue',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='blockedissue',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='weather_locked_at',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='weather_override_note',
        ),
        migrations.RemoveField(
            model_name='equipmentusage',
            name='master_code',
        ),
        migrations.RemoveField(
            model_name='equipmentusage',
            name='usage_type',
        ),
        migrations.RemoveField(
            model_name='materialreceipt',
            name='delivery_note',
        ),
        migrations.RemoveField(
            model_name='materialreceipt',
            name='master_code',
        ),
        migrations.RemoveField(
            model_name='materialreceipt',
            name='order_reference',
        ),
        migrations.RemoveField(
            model_name='materialreceipt',
            name='uom',
        ),
        migrations.RemoveField(
            model_name='sitevisit',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='sitevisit',
            name='visit_type',
        ),
        migrations.RemoveField(
            model_name='workforceentry',
            name='master_code',
        ),
        migrations.RemoveField(
            model_name='workforceentry',
            name='regular_hours',
        ),
        migrations.RemoveField(
            model_name='workforceentry',
            name='skill_level',
        ),
        migrations.RemoveField(
            model_name='workforceentry',
            name='worker_name',
        ),
        migrations.RemoveField(
            model_name='workforceentry',
            name='workforce_type',
        ),
        migrations.RemoveField(
            model_name='workprogress',
            name='qc_result',
        ),
        migrations.RemoveField(
            model_name='workprogress',
            name='status',
        ),
        migrations.AddField(
            model_name='blockedissue',
            name='action_required',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='blockedissue',
            name='impact',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='blockedissue',
            name='issue',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='blockedissue',
            name='responsible_party',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='blockedissue',
            name='status',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='general_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='equipmentusage',
            name='idle_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='equipmentusage',
            name='working_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='materialreceipt',
            name='delivery_note_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='materialreceipt',
            name='material_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='materialreceipt',
            name='supplier',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='materialreceipt',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='company',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='purpose',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='visit_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceentry',
            name='manpower_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workforceentry',
            name='normal_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='workforceentry',
            name='trade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workforce_trade_entries', to='reports.lookupitem'),
        ),
        migrations.AddField(
            model_name='workprogress',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workprogress',
            name='location',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='workprogress',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='workprogress',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='blockedissue',
            name='daily_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_issues', to='reports.dailyreport'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_reports', to='reports.project'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='reference_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='weather_condition',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='weather_source',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('api_confirmed', 'API Confirmed'), ('manual_override', 'Manual Override')], default='manual', max_length=30),
        ),
        migrations.AlterField(
            model_name='equipmentusage',
            name='daily_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_usages', to='reports.dailyreport'),
        ),
        migrations.AlterField(
            model_name='equipmentusage',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.equipmentmaster'),
        ),
        migrations.AlterField(
            model_name='equipmentusage',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='equipmentusage',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='materialreceipt',
            name='daily_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_receipts', to='reports.dailyreport'),
        ),
        migrations.AlterField(
            model_name='materialreceipt',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='materialreceipt',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='daily_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to='reports.dailyreport'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='visitor_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='workforceentry',
            name='daily_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workforce_entries', to='reports.dailyreport'),
        ),
        migrations.AlterField(
            model_name='workforceentry',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='workforceentry',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='workprogress',
            name='daily_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_progress_items', to='reports.dailyreport'),
        ),
        migrations.AlterField(
            model_name='workprogress',
            name='master_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.mastercode'),
        ),
        migrations.AlterField(
            model_name='workprogress',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dailyreportchangelog',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyreportchangelog',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='reports.dailyreport'),
        ),
    ]
