# Generated by Django 5.2.13 on 2026-05-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_dailyreportchangelog_alter_blockedissue_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='updated_at',
        ),
    ]
