# Generated by Django 5.2.13 on 2026-05-14 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_dailyreportattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedissue',
            name='master_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.mastercode'),
        ),
        migrations.AddField(
            model_name='equipmentusage',
            name='master_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.mastercode'),
        ),
        migrations.AddField(
            model_name='materialreceipt',
            name='master_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.mastercode'),
        ),
        migrations.AddField(
            model_name='workforceentry',
            name='master_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.mastercode'),
        ),
    ]
