# Generated by Django 5.2.13 on 2026-05-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_blockedissue_master_code_equipmentusage_master_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mastercode',
            options={'ordering': ['project_phase__display_order', 'category__symbol', 'subcategory__symbol']},
        ),
        migrations.AlterUniqueTogether(
            name='mastercode',
            unique_together=set(),
        ),
    ]
