# Generated by Django 6.0.5 on 2026-05-20 09:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_alter_mastercode_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mastercode',
            options={'ordering': ['project_phase__display_order', 'category__symbol', 'subcategory__symbol'], 'verbose_name': 'Master Code', 'verbose_name_plural': 'Master Codes'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['code', 'name']},
        ),
        migrations.RemoveField(
            model_name='blockedissue',
            name='action_required',
        ),
        migrations.RemoveField(
            model_name='blockedissue',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sitevisit',
            name='company',
        ),
        migrations.RemoveField(
            model_name='workprogress',
            name='location',
        ),
        migrations.AddField(
            model_name='blockedissue',
            name='amended_solution',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='blockedissue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='blockedissue',
            name='escalated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_blocked_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blockedissue',
            name='pm_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('pm_review', 'PM Review'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=30),
        ),
        migrations.AddField(
            model_name='blockedissue',
            name='priority',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='blockedissue',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='blockedissue',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blockedissue',
            name='suggested_solution',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='blockedissue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_daily_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='weather_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dailyreportattachment',
            name='section',
            field=models.CharField(choices=[('general', 'General'), ('active_work', 'Active Work'), ('blocked_issue', 'Blocked Issue'), ('site_visit', 'Site Visit'), ('workforce', 'Workforce'), ('equipment', 'Equipment'), ('material', 'Material'), ('other', 'Other')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='authority',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='building_floors_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='permit_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='permit_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='visit_code',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'list_type': 'site_visit_code'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_visit_code_entries', to='reports.lookupitem'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='visitor_entity',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='reference_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('returned', 'Returned for Correction')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='lookupitem',
            name='list_type',
            field=models.CharField(choices=[('qc_result', 'QC Result'), ('severity', 'Severity'), ('followup', 'Follow Up'), ('workforce', 'Workforce'), ('skill_level', 'Skill Level'), ('usage_type', 'Usage Type'), ('uom', 'UOM'), ('status', 'Status'), ('visit_type', 'Visit Type'), ('site_visit_code', 'Site Visit Code'), ('issue_priority', 'Issue Priority'), ('issue_status', 'Issue Status')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='mastercode',
            unique_together={('project_phase', 'category', 'subcategory', 'document_type')},
        ),
        migrations.CreateModel(
            name='ProjectArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('area_type', models.CharField(choices=[('basement', 'Basement'), ('floor', 'Floor'), ('roof', 'Roof'), ('external', 'External Area'), ('parking', 'Parking'), ('common', 'Common Area'), ('other', 'Other')], default='floor', max_length=30)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='reports.project')),
            ],
            options={
                'verbose_name': 'Project Area',
                'verbose_name_plural': 'Project Areas',
                'ordering': ['project__code', 'sort_order', 'code'],
                'unique_together': {('project', 'code')},
            },
        ),
        migrations.AddField(
            model_name='workprogress',
            name='project_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_progress_items', to='reports.projectarea'),
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('site_engineer', 'Site Engineer'), ('project_manager', 'Project Manager'), ('department_manager', 'Department Manager'), ('operation', 'Operation / Back Office'), ('cost_control', 'Cost Control')], max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='reports.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Assignment',
                'verbose_name_plural': 'Project Assignments',
                'ordering': ['project__code', 'role', 'user__username'],
                'unique_together': {('project', 'user', 'role')},
            },
        ),
    ]
