# Generated by Django 6.0.5 on 2026-05-21 12:58

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_alter_mastercode_options_alter_project_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mastercode',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='blockedissue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mastercode',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=18, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together={('project', 'reference_date', 'created_by')},
        ),
        migrations.AddConstraint(
            model_name='mastercode',
            constraint=models.UniqueConstraint(fields=('code', 'document_type'), name='unique_code_document_type'),
        ),
    ]
