# Generated by Django 6.0.5 on 2026-05-21 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_alter_mastercode_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mastercode',
            name='unique_code_document_type',
        ),
        migrations.AlterUniqueTogether(
            name='mastercode',
            unique_together={('project_phase', 'category', 'subcategory')},
        ),
        migrations.RemoveField(
            model_name='mastercode',
            name='document_type',
        ),
    ]
