# Generated by Django 6.0.5 on 2026-05-21 20:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_remove_mastercode_unique_code_document_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workforceentry',
            options={'ordering': ['worker_name']},
        ),
        migrations.RemoveField(
            model_name='workforceentry',
            name='manpower_count',
        ),
        migrations.RemoveField(
            model_name='workforceentry',
            name='trade',
        ),
        migrations.AddField(
            model_name='workforceentry',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='workforceentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workforceentry',
            name='skill_level',
            field=models.CharField(blank=True, choices=[('certified', 'Certified'), ('skilled', 'Skilled Worker'), ('helper', 'Helper'), ('supervisor', 'Supervisor'), ('operator', 'Operator'), ('technician', 'Technician')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='workforceentry',
            name='worker_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='workforceentry',
            name='worker_source',
            field=models.CharField(blank=True, choices=[('company', 'Company Direct'), ('subcontractor', 'Subcontractor'), ('workshop', 'Workshop'), ('temporary', 'Temporary Labor'), ('supplier_team', 'Supplier Team')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='dailyreportattachment',
            name='daily_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_attachments', to='reports.dailyreport'),
        ),
        migrations.AlterField(
            model_name='dailyreportattachment',
            name='file',
            field=models.FileField(upload_to='daily_reports/general/'),
        ),
        migrations.AlterField(
            model_name='dailyreportattachment',
            name='section',
            field=models.CharField(choices=[('general', 'General'), ('other', 'Other')], default='general', max_length=50),
        ),
        migrations.CreateModel(
            name='BlockedIssueAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, default='', max_length=100)),
                ('file', models.FileField(upload_to='daily_reports/blocked_issues/')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.blockedissue')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, default='', max_length=100)),
                ('file', models.FileField(upload_to='daily_reports/equipment/')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('equipment_usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.equipmentusage')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, default='', max_length=100)),
                ('file', models.FileField(upload_to='daily_reports/materials/')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('material_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.materialreceipt')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteVisitAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, default='', max_length=100)),
                ('file', models.FileField(upload_to='daily_reports/site_visits/')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('site_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.sitevisit')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('worker_source', models.CharField(choices=[('company', 'Company Direct'), ('subcontractor', 'Subcontractor'), ('workshop', 'Workshop'), ('temporary', 'Temporary Labor'), ('supplier_team', 'Supplier Team')], default='company', max_length=50)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('skill_level', models.CharField(blank=True, choices=[('certified', 'Certified'), ('skilled', 'Skilled Worker'), ('helper', 'Helper'), ('supervisor', 'Supervisor'), ('operator', 'Operator'), ('technician', 'Technician')], default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'worker_source', 'company_name')},
            },
        ),
        migrations.AddField(
            model_name='workforceentry',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_entries', to='reports.workerprofile'),
        ),
        migrations.CreateModel(
            name='WorkforceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, default='', max_length=100)),
                ('file', models.FileField(upload_to='daily_reports/workforce/')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workforce_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.workforceentry')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkProgressAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, default='', max_length=100)),
                ('file', models.FileField(upload_to='daily_reports/active_works/')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.workprogress')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
