# Generated by Django 6.0.5 on 2026-05-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_alter_workforceentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='returned_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='review_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted for Review'), ('approved', 'Approved'), ('returned', 'Returned for Correction'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
