# Generated by Django 6.0.5 on 2026-05-28 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0025_useractivitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedissue',
            name='follow_up_with',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='blockedissue',
            name='pm_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='blockedissue',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blockedissue',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_blocked_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
