# Generated by Django 6.0.5 on 2026-06-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0026_blockedissue_follow_up_with_blockedissue_pm_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workforceentry',
            options={'ordering': ['entry_type', 'worker__name', 'external_source_name']},
        ),
        migrations.RenameField(
            model_name='workforceentry',
            old_name='worker_name',
            new_name='external_source_name',
        ),
        migrations.RemoveField(
            model_name='workforceentry',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='workforceentry',
            name='normal_hours',
        ),
        migrations.RemoveField(
            model_name='workforceentry',
            name='overtime_hours',
        ),
        migrations.RemoveField(
            model_name='workforceentry',
            name='worker_source',
        ),
        migrations.AddField(
            model_name='workforceentry',
            name='attendance_status',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='workforceentry',
            name='entry_type',
            field=models.CharField(choices=[('rd_worker', 'RD Worker Attendance'), ('external', 'External Workforce')], default='rd_worker', max_length=30),
        ),
        migrations.AddField(
            model_name='workforceentry',
            name='external_source_type',
            field=models.CharField(blank=True, choices=[('subcontractor', 'Subcontractor'), ('rental', 'Rental'), ('workshop', 'Workshop')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='workforceentry',
            name='login_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceentry',
            name='logout_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceentry',
            name='number_of_workers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforceentry',
            name='sent_to_other_project',
            field=models.BooleanField(default=False),
        ),
    ]
