# Generated by Django 6.0.5 on 2026-06-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0027_alter_workforceentry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workforceentry',
            options={'ordering': ['entry_type', 'external_source_type', 'worker__name', 'worker_name', 'external_source_name']},
        ),
        migrations.RemoveField(
            model_name='workforceentry',
            name='attendance_status',
        ),
        migrations.AddField(
            model_name='workforceentry',
            name='trade_work_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='workforceentry',
            name='worker_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='workforceentry',
            name='entry_type',
            field=models.CharField(choices=[('rd_worker', 'RD Worker'), ('external', 'External Labor')], default='rd_worker', max_length=30),
        ),
        migrations.AlterField(
            model_name='workforceentry',
            name='external_source_type',
            field=models.CharField(blank=True, choices=[('subcontractor', 'Subcontractor'), ('rental', 'By Rent')], default='', max_length=50),
        ),
    ]
